// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "haert":return img`
....................
....................
....................
....................
....................
....................
.......22...22......
......2322.2222.....
......232222222.....
......222222222.....
.......22222b2......
........222b2.......
.........222........
..........2.........
....................
....................
....................
....................
....................
....................
`;
            case "image2":
            case "bad guy":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . 2 2 2 2 . . . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . . 2 1 2 2 1 2 . . . . . 
. . . . 2 1 f 1 1 f 1 2 . . . . 
. . 2 2 2 2 1 2 2 1 2 2 2 . . . 
. . 2 2 2 2 2 2 2 2 2 2 2 . . . 
. 2 2 2 2 2 2 2 2 2 2 2 2 . . . 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
2 2 2 . 2 2 2 2 2 2 . . 2 2 2 . 
2 2 . . 2 2 2 2 2 2 . . 2 2 2 . 
2 . . . 2 2 2 2 2 2 . . . 2 2 . 
. . . . 2 2 2 2 2 2 . . . . . . 
`;
            case "image3":
            case "player 2":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image4":
            case "player 6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . c d 5 d c . . . . . 
. . . b c c d 5 5 5 d c c b . . 
. . b d d 5 5 5 5 5 5 5 d d b . 
. . . b c c d 5 5 5 d c c b . . 
. . . . . . c d 5 d c . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "player":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . c d 5 d c . . . . . 
. . . b c c d 5 5 5 d c c b . . 
. . b d d 5 5 5 5 5 5 5 d d b . 
. . . b c c d 5 5 5 d c c b . . 
. . . . . . c d 5 d c . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
